server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Services
external-services:
  auth:
    service:
      url: http://pump-auth-service:8080

# Logging
logging:
  level:
    com.johnmartin.social: INFO
