spring:
  application:
    name: pump-social-service

  data:
    mongodb:
      auto-index-creation: true

# Logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

# Open AI
openai:
  api-key: ${OPENAI_API_KEY}

# Internal token
pump:
  security:
    internal-service-token: ${PUMP_INTERNAL_SERVICE_TOKEN}