package com.johnmartin.social.service;

import java.util.List;

import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

import com.johnmartin.social.constants.UIConstants;
import com.johnmartin.social.constants.api.ApiErrorMessages;
import com.johnmartin.social.dto.AuthUser;
import com.johnmartin.social.dto.request.CreateCommentRequest;
import com.johnmartin.social.dto.response.CommentResponse;
import com.johnmartin.social.entities.CommentEntity;
import com.johnmartin.social.entities.PostEntity;
import com.johnmartin.social.entities.UserEntity;
import com.johnmartin.social.exception.BadRequestException;
import com.johnmartin.social.exception.NotFoundException;
import com.johnmartin.social.exception.UnauthorizedException;
import com.johnmartin.social.mapper.CommentMapper;
import com.johnmartin.social.repository.CommentRepository;
import com.johnmartin.social.security.AuthContext;
import com.johnmartin.social.utilities.LoggerUtility;

import jakarta.transaction.Transactional;

@Service
public class CommentService {

    private static final Class<CommentService> clazz = CommentService.class;

    private final CommentRepository commentRepository;
    private final PostService postService;
    private final UserService userService;

    public CommentService(CommentRepository commentRepository, PostService postService, UserService userService) {
        this.commentRepository = commentRepository;
        this.postService = postService;
        this.userService = userService;
    }

    /**
     * Get comments
     * 
     * @param postId
     *            - Post ID
     * @param page
     *            - page
     * @return List of CommentResponse
     */
    public List<CommentResponse> getComments(String postId, UserEntity user, int page) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [getComments] postId: [%s] user: [%s] page: [%s]",
                                      postId,
                                      user,
                                      page));

        PageRequest pageRequest = PageRequest.of(page, UIConstants.MINIMUM_COMMENTS_PER_POST);
        List<CommentEntity> commentEntityList = commentRepository.findByPostIdOrderByCreatedAtDesc(postId, pageRequest);
        return commentEntityList.stream().map(comment -> CommentMapper.toResponse(comment, user)).toList();
    }

    /**
     * Create a comment
     *
     * @param postId
     *            - Post ID
     * @param request
     *            - CreateCommentRequest
     * @return CommentResponse
     */
    public CommentResponse createComment(String postId, CreateCommentRequest request) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [createComment] postId: [%s] request: [%s]", postId, request));

        if (request == null) {
            LoggerUtility.d(clazz, "Request is null, will not proceed method call");
            throw new BadRequestException(ApiErrorMessages.INVALID_REQUEST);
        }

        if (StringUtils.isBlank(postId)) {
            LoggerUtility.d(clazz, "Post ID is null, will not proceed with create comment API");
            throw new BadRequestException(ApiErrorMessages.Post.POST_ID_IS_REQUIRED);
        }

        AuthUser authUser = AuthContext.get();
        if (authUser == null) {
            LoggerUtility.d(clazz, "Auth user is null, will throw unauthorized exception");
            throw new UnauthorizedException(ApiErrorMessages.User.USER_IS_NOT_AUTHENTICATED);
        }

        PostEntity post = postService.getPostById(postId);
        UserEntity user = userService.findByEmail(authUser.email());

        CommentEntity createdComment = new CommentEntity();
        createdComment.setComment(request.comment());
        createdComment.setAuthorId(user.getId());
        createdComment.setPostId(post.getId());
        createdComment.setLikesCount(0);
        createdComment.setRepliesCount(0);

        // ID and Dates are generated by MongoDB after insertion
        CommentEntity commentToBeReturned = saveComment(createdComment);
        LoggerUtility.t(clazz, String.format("commentToBeReturned: [%s]", commentToBeReturned));
        return CommentMapper.toResponse(commentToBeReturned, user);
    }

    /**
     * Delete a comment
     *
     * @param commentId
     *            - Comment ID
     */
    public void deleteComment(String postId, String commentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [deleteComment] postId: [%s] commentId: [%s]",
                                      postId,
                                      commentId));

        if (StringUtils.isBlank(postId)) {
            LoggerUtility.d(clazz, "Post ID is null, will not proceed with delete comment API");
            throw new BadRequestException(ApiErrorMessages.Post.POST_ID_IS_REQUIRED);
        }

        if (StringUtils.isBlank(commentId)) {
            LoggerUtility.d(clazz, "Comment ID is null, will not proceed with delete comment API");
            throw new BadRequestException(ApiErrorMessages.Comment.COMMENT_ID_IS_REQUIRED);
        }

        AuthUser authUser = AuthContext.get();
        if (authUser == null) {
            LoggerUtility.d(clazz, "Auth user is null, will throw unauthorized exception");
            throw new UnauthorizedException(ApiErrorMessages.User.USER_IS_NOT_AUTHENTICATED);
        }

        PostEntity post = postService.getPostById(postId);
        CommentEntity comment = getCommentById(commentId);
        UserEntity user = userService.findByEmail(authUser.email());

        // Ensure comment belongs to the post
        if (!comment.getPostId().equals(post.getId())) {
            throw new BadRequestException(ApiErrorMessages.Comment.THE_COMMENT_DOES_NOT_BELONG_TO_THE_SPECIFIED_POST);
        }

        // Only comment owner can delete
        if (!comment.getAuthorId().equals(user.getId())) {
            throw new UnauthorizedException(ApiErrorMessages.User.YOU_ARE_NOT_AUTHORIZED_TO_PERFORM_THIS_ACTION);
        }

        // Delete comment
        commentRepository.deleteById(comment.getId());

        // Decrement post comment count
        postService.decrementCommentsCount(post.getId());
    }

    /**
     * Save a comment then increment post's comments count
     * 
     * @param comment
     *            - Comment
     * @return CommentEntity
     */
    @Transactional
    public CommentEntity saveComment(CommentEntity comment) {
        LoggerUtility.d(clazz, String.format("Execute method: [saveComment] comment: [%s]", comment));
        CommentEntity savedComment = commentRepository.save(comment);
        postService.incrementCommentsCount(comment.getPostId());
        return savedComment;
    }

    /**
     * Like a comment
     *
     * @param postId
     *            - Post ID
     *
     * @param commentId
     *            - Comment ID
     * @return CommentResponse
     */
    public CommentResponse likeComment(String postId, String commentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [likeComment] postId: [%s] commentId: [%s]", postId, commentId));

        if (StringUtils.isBlank(postId)) {
            LoggerUtility.d(clazz, "Post ID is null, will not proceed with like comment API");
            throw new BadRequestException(ApiErrorMessages.Post.POST_ID_IS_REQUIRED);
        }

        if (StringUtils.isBlank(commentId)) {
            LoggerUtility.d(clazz, "Comment ID is null, will not proceed with like comment API");
            throw new BadRequestException(ApiErrorMessages.Comment.COMMENT_ID_IS_REQUIRED);
        }

        AuthUser authUser = AuthContext.get();
        if (authUser == null) {
            LoggerUtility.d(clazz, "Auth user is null, will throw unauthorized exception");
            throw new UnauthorizedException(ApiErrorMessages.User.USER_IS_NOT_AUTHENTICATED);
        }

        CommentEntity comment = getCommentById(commentId);
        UserEntity user = userService.findByEmail(authUser.email());

        // If user already liked the comment, unlike
        if (CollectionUtils.containsAny(comment.getLikedByUserIds(), user.getId())) {
            applyUnlikeComment(user.getId(), comment.getId());
        } else {
            applyLikeComment(user.getId(), comment.getId());
        }

        // Get updated post to get updated like state
        CommentEntity updatedComment = getCommentById(comment.getId());
        LoggerUtility.t(clazz, String.format("updatedComment: [%s]", updatedComment));
        return CommentMapper.toResponse(updatedComment, user);
    }

    /**
     * Delete all comments from a Post
     * 
     * @param postId
     *            - Post ID
     */
    public void deleteByPostId(String postId) {
        LoggerUtility.d(clazz, String.format("Execute method: [deleteByPostId] postId: [%s]", postId));
        PostEntity post = postService.getPostById(postId);
        commentRepository.deleteByPostId(post.getId());
    }

    /**
     * Get comment by ID
     *
     * @param commentId
     *            - Comment ID
     * @return CommentEntity
     */
    private CommentEntity getCommentById(String commentId) {
        LoggerUtility.d(clazz, String.format("Execute method: [getCommentById] commentId: [%s]", commentId));
        return commentRepository.findById(commentId)
                                .orElseThrow(() -> new NotFoundException(ApiErrorMessages.Comment.COMMENT_NOT_FOUND));
    }

    /**
     * Like a comment
     * 
     * @param userId
     *            - User ID
     * @param commentId
     *            - Comment ID
     */
    public void applyLikeComment(String userId, String commentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [applyLikeComment] userId: [%s] commentId: [%s]",
                                      userId,
                                      commentId));
        commentRepository.likeComment(userId, commentId);
    }

    /**
     * Unlike a comment
     * 
     * @param userId
     *            - User ID
     * @param commentId
     *            - Comment ID
     */
    public void applyUnlikeComment(String userId, String commentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [applyUnlikeComment] userId: [%s] commentId: [%s]",
                                      userId,
                                      commentId));
        commentRepository.unlikeComment(userId, commentId);
    }
}
