package com.johnmartin.social.service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import org.apache.commons.collections4.CollectionUtils;
import org.springframework.stereotype.Service;

import com.johnmartin.social.constants.UIConstants;
import com.johnmartin.social.constants.error.AuthErrorConstants;
import com.johnmartin.social.constants.error.domain.CommentErrorConstants;
import com.johnmartin.social.dto.AuthUser;
import com.johnmartin.social.dto.response.CommentResponse;
import com.johnmartin.social.entities.CommentEntity;
import com.johnmartin.social.entities.PostEntity;
import com.johnmartin.social.entities.UserEntity;
import com.johnmartin.social.exception.BadRequestException;
import com.johnmartin.social.exception.NotFoundException;
import com.johnmartin.social.exception.UnauthorizedException;
import com.johnmartin.social.mapper.CommentMapper;
import com.johnmartin.social.repository.CommentLikeRepository;
import com.johnmartin.social.repository.CommentRepository;
import com.johnmartin.social.utilities.LoggerUtility;

import jakarta.transaction.Transactional;

@Service
public class CommentService {

    private static final Class<CommentService> clazz = CommentService.class;

    private final CommentRepository commentRepository;

    private final PostService postService;
    private final UserService userService;
    private final CommentLikeService commentLikeService;
    private final AuthService authService;

    public CommentService(CommentRepository commentRepository,
                          CommentLikeRepository commentLikeRepository,
                          PostService postService,
                          UserService userService,
                          CommentLikeService commentLikeService,
                          AuthService authService) {
        this.commentRepository = commentRepository;
        this.postService = postService;
        this.userService = userService;
        this.commentLikeService = commentLikeService;
        this.authService = authService;
    }

    /**
     * Create a comment
     *
     * @param postId
     *            - Post ID
     * @param comment
     *            - comment
     * @return CommentResponse
     */
    public CommentResponse createComment(String postId, String comment) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [createComment] postId: [%s] comment: [%s]", postId, comment));

        // Get auth user
        AuthUser authUser = authService.getAuthUser();

        // Get post
        PostEntity post = postService.getPostById(postId);

        // Create a comment
        CommentEntity createdComment = new CommentEntity();
        createdComment.setComment(comment);
        createdComment.setAuthorId(authUser.id());
        createdComment.setPostId(post.getId());
        createdComment.setLikesCount(0);
        createdComment.setRepliesCount(0);

        LoggerUtility.t(clazz, String.format("createdComment: [%s]", createdComment));

        // ID and Dates are generated by MongoDB after insertion
        CommentEntity savedComment = commentRepository.save(createdComment);
        LoggerUtility.t(clazz, String.format("savedComment: [%s]", savedComment));

        // Increment comments count of that post
        postService.incrementCommentsCount(savedComment.getPostId());

        boolean isLiked = commentLikeService.isCommentLikedByUser(savedComment.getId(), authUser.id());
        // Get social user
        UserEntity socialUser = userService.findById(authUser.id());
        return CommentMapper.toResponse(savedComment, socialUser, isLiked);
    }

    /**
     * Delete a comment
     *
     * @param commentId
     *            - Comment ID
     */
    @Transactional
    public void deleteComment(String postId, String commentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [deleteComment] postId: [%s] commentId: [%s]",
                                      postId,
                                      commentId));

        // Get auth user
        AuthUser authUser = authService.getAuthUser();

        // Get post
        PostEntity post = postService.getPostById(postId);

        // Get comment
        CommentEntity comment = getCommentById(commentId);

        // Get social user
        UserEntity user = userService.findById(authUser.id());

        // Ensure comment belongs to the post
        if (!comment.getPostId().equals(post.getId())) {
            throw new BadRequestException(CommentErrorConstants.THE_COMMENT_DOES_NOT_BELONG_TO_THE_SPECIFIED_POST);
        }

        // Only comment owner can delete
        if (!comment.getAuthorId().equals(user.getId())) {
            throw new UnauthorizedException(AuthErrorConstants.YOU_ARE_NOT_AUTHORIZED_TO_PERFORM_THIS_ACTION);
        }

        try {
            // Delete comment
            commentRepository.deleteById(commentId);

            // Delete likes for comments
            commentLikeService.deleteByCommentId(commentId);

            // Decrement post comment count
            postService.decrementCommentsCount(postId);
        } catch (Exception e) {
            LoggerUtility.e(clazz, String.format("Failed to delete comment. error: [%s]", e.getMessage()), e);
        }
    }

    /**
     * Like a comment
     *
     * @param postId
     *            - Post ID
     *
     * @param commentId
     *            - Comment ID
     * @return CommentResponse
     */
    public CommentResponse likeComment(String postId, String commentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [likeComment] postId: [%s] commentId: [%s]", postId, commentId));

        // Get auth user
        AuthUser authUser = authService.getAuthUser();

        // Get comment
        CommentEntity comment = getCommentById(commentId);
        LoggerUtility.t(clazz, String.format("comment: [%s]", comment));

        boolean isLiked = commentLikeService.toggleLike(comment.getId(), authUser.id());
        // Get social user
        UserEntity socialUser = userService.findById(authUser.id());
        return CommentMapper.toResponse(comment, socialUser, isLiked);
    }

    /**
     * Delete all comments from a Post
     * 
     * @param postId
     *            - Post ID
     */
    public void deleteByPostId(String postId) {
        LoggerUtility.d(clazz, String.format("Execute method: [deleteByPostId] postId: [%s]", postId));
        commentRepository.deleteByPostId(postId);
    }

    /**
     * Get comment by ID
     *
     * @param commentId
     *            - Comment ID
     * @return CommentEntity
     */
    private CommentEntity getCommentById(String commentId) {
        LoggerUtility.d(clazz, String.format("Execute method: [getCommentById] commentId: [%s]", commentId));
        return commentRepository.findById(commentId).orElseThrow(() -> new NotFoundException("Comment not found"));
    }

    /**
     * Get latest comments of all posts
     * 
     * @param postIds
     *            - Post IDs
     * @param socialUser
     *            - Social user
     * @return Map<String, List<CommentResponse>>
     */
    public Map<String, List<CommentResponse>> getLatestCommentsByPostIds(List<String> postIds, UserEntity socialUser) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [getLatestCommentsByPostIds] postIds: [%s] socialUser: [%s]",
                                      postIds,
                                      socialUser));

        // Get latest comments
        List<CommentEntity> comments = commentRepository.findByPostIdInOrderByCreatedAtDesc(postIds);
        LoggerUtility.d(clazz, String.format("comments size: [%s]", comments.size()));

        if (CollectionUtils.isEmpty(comments)) {
            return new HashMap<>();
        }

        // Extract all comments's id
        List<String> commentIds = comments.stream().map(CommentEntity::getId).toList();
        // Get likedCommentIds
        Set<String> likedPostIds = commentLikeService.getLikedCommentIds(commentIds, socialUser.getId());
        return comments.stream()
                       .map(comment -> CommentMapper.toResponse(comment,
                                                                socialUser,
                                                                likedPostIds.contains(comment.getId())))
                       .collect(Collectors.groupingBy(CommentResponse::postId,
                                                      Collectors.collectingAndThen(Collectors.toList(),
                                                                                   list -> list.stream()
                                                                                               .limit(UIConstants.MINIMUM_COMMENTS_PER_POST)
                                                                                               .toList())));
    }
}
