package com.johnmartin.social.service;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

import org.apache.commons.collections4.CollectionUtils;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

import com.johnmartin.social.constants.UIConstants;
import com.johnmartin.social.constants.error.AuthErrorConstants;
import com.johnmartin.social.constants.error.domain.CommentErrorConstants;
import com.johnmartin.social.dto.AuthUser;
import com.johnmartin.social.dto.response.CommentResponse;
import com.johnmartin.social.dto.response.common.PagedResponse;
import com.johnmartin.social.entities.CommentEntity;
import com.johnmartin.social.entities.PostEntity;
import com.johnmartin.social.entities.UserEntity;
import com.johnmartin.social.exception.BadRequestException;
import com.johnmartin.social.exception.NotFoundException;
import com.johnmartin.social.exception.UnauthorizedException;
import com.johnmartin.social.mapper.CommentMapper;
import com.johnmartin.social.repository.CommentLikeRepository;
import com.johnmartin.social.repository.CommentRepository;
import com.johnmartin.social.utilities.LoggerUtility;
import com.johnmartin.social.utils.ExtractorUtils;

import jakarta.transaction.Transactional;

@Service
public class CommentService {

    private static final Class<CommentService> clazz = CommentService.class;

    private final CommentRepository commentRepository;

    private final PostService postService;
    private final UserService userService;
    private final CommentLikeService commentLikeService;
    private final AuthService authService;

    public CommentService(CommentRepository commentRepository,
                          CommentLikeRepository commentLikeRepository,
                          PostService postService,
                          UserService userService,
                          CommentLikeService commentLikeService,
                          AuthService authService) {
        this.commentRepository = commentRepository;
        this.postService = postService;
        this.userService = userService;
        this.commentLikeService = commentLikeService;
        this.authService = authService;
    }

    /**
     * Create a comment
     *
     * @param postId
     *            - Post ID
     * @param comment
     *            - comment
     * @return CommentResponse
     */
    public CommentResponse createComment(String postId, String comment, String parentCommentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [createComment] postId: [%s] parentCommentId: [%s] comment: [%s]",
                                      postId,
                                      parentCommentId,
                                      comment));

        // Get auth user
        AuthUser authUser = authService.getAuthUser();

        // Get post
        PostEntity post = postService.getPostById(postId);

        // Create a comment
        CommentEntity createdComment = new CommentEntity();
        createdComment.setComment(comment);
        createdComment.setAuthorId(authUser.id());
        createdComment.setPostId(post.getId());
        createdComment.setParentCommentId(parentCommentId);
        createdComment.setLikesCount(0);
        createdComment.setRepliesCount(0);

        LoggerUtility.t(clazz, String.format("createdComment: [%s]", createdComment));

        // ID and Dates are generated by MongoDB after insertion
        CommentEntity savedComment = commentRepository.save(createdComment);
        LoggerUtility.t(clazz, String.format("savedComment: [%s]", savedComment));

        // If parentCommentId, the comment is the top-level comment
        if (parentCommentId == null) {
            // Increment comments count of post
            postService.incrementCommentsCount(postId);
        } else {
            // reply
            incrementRepliesCount(parentCommentId);
        }

        // Get social user
        UserEntity socialUser = userService.findById(authUser.id());
        return CommentMapper.toResponse(savedComment, socialUser, false);
    }

    /**
     * Create a reply under a comment
     * 
     * @param postId
     *            - Post ID
     * @param commentId
     *            - Parent comment ID
     * @param comment
     *            - Comment
     * @return CommentResponse
     */
    public CommentResponse createReply(String postId, String commentId, String comment) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [createReply] postId: [%s] commentId: [%s] comment: [%s]",
                                      postId,
                                      commentId,
                                      comment));

        // Get parent comment
        CommentEntity parentComment = getCommentById(commentId);

        // Check if comment belongs to the post
        if (!parentComment.getPostId().equals(postId)) {
            throw new BadRequestException(CommentErrorConstants.THE_COMMENT_DOES_NOT_BELONG_TO_THE_SPECIFIED_POST);
        }

        // If replying to something that is already a reply, reject
        if (parentComment.getParentCommentId() != null) {
            throw new BadRequestException(CommentErrorConstants.NESTED_REPLIES_ARE_NOT_ALLOWED);
        }

        return createComment(parentComment.getPostId(), // safe source of truth
                             comment,
                             commentId // parentCommentId
        );
    }

    /**
     * Increment replies count
     *
     * @param commentId
     *            - Comment ID
     */
    public void incrementRepliesCount(String commentId) {
        LoggerUtility.d(clazz, String.format("Execute method: [incrementRepliesCount] commentId: [%s]", commentId));
        commentRepository.incrementRepliesCount(commentId);
    }

    /**
     * Delete a comment
     *
     * @param commentId
     *            - Comment ID
     */
    @Transactional
    public void deleteComment(String postId, String commentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [deleteComment] postId: [%s] commentId: [%s]",
                                      postId,
                                      commentId));

        // Get auth user
        AuthUser authUser = authService.getAuthUser();

        // Get post
        PostEntity post = postService.getPostById(postId);

        // Get comment
        CommentEntity comment = getCommentById(commentId);

        // Get social user
        UserEntity user = userService.findById(authUser.id());

        // Ensure comment belongs to the post
        if (!comment.getPostId().equals(post.getId())) {
            throw new BadRequestException(CommentErrorConstants.THE_COMMENT_DOES_NOT_BELONG_TO_THE_SPECIFIED_POST);
        }

        // Only comment owner can delete
        if (!comment.getAuthorId().equals(user.getId())) {
            throw new UnauthorizedException(AuthErrorConstants.YOU_ARE_NOT_AUTHORIZED_TO_PERFORM_THIS_ACTION);
        }

        try {
            // Delete comment
            commentRepository.deleteById(commentId);

            // Delete likes for comments
            commentLikeService.deleteByCommentId(commentId);

            // Decrement post comment count
            postService.decrementCommentsCount(postId);
        } catch (Exception e) {
            LoggerUtility.e(clazz, String.format("Failed to delete comment. error: [%s]", e.getMessage()), e);
        }
    }

    /**
     * Like a comment
     *
     * @param postId
     *            - Post ID
     *
     * @param commentId
     *            - Comment ID
     * @return CommentResponse
     */
    public CommentResponse likeComment(String postId, String commentId) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [likeComment] postId: [%s] commentId: [%s]", postId, commentId));

        // Get auth user
        AuthUser authUser = authService.getAuthUser();

        // Get comment
        CommentEntity comment = getCommentById(commentId);
        LoggerUtility.t(clazz, String.format("comment: [%s]", comment));

        boolean isLiked = commentLikeService.toggleLike(comment.getId(), authUser.id());
        // Get social user
        UserEntity socialUser = userService.findById(authUser.id());
        return CommentMapper.toResponse(comment, socialUser, isLiked);
    }

    /**
     * Delete all comments from a Post
     * 
     * @param postId
     *            - Post ID
     */
    public void deleteByPostId(String postId) {
        LoggerUtility.d(clazz, String.format("Execute method: [deleteByPostId] postId: [%s]", postId));
        commentRepository.deleteByPostId(postId);
    }

    /**
     * Get latest comments of all posts
     * 
     * @param postIds
     *            - Post IDs
     * @param socialUser
     *            - Social User
     * @return Map<String, List<CommentResponse>>
     */
    public Map<String, List<CommentResponse>> getLatestCommentsByPostIds(List<String> postIds, UserEntity socialUser) {
        LoggerUtility.d(clazz, String.format("Execute method: [getLatestCommentsByPostIds] postIds: [%s]", postIds));

        // Get latest comments
        List<CommentEntity> comments = commentRepository.findByPostIdInOrderByCreatedAtDesc(postIds);
        LoggerUtility.d(clazz, String.format("comments size: [%s]", comments.size()));

        if (CollectionUtils.isEmpty(comments)) {
            LoggerUtility.d(clazz, "comments are empty");
            return new HashMap<>();
        }

        // Get authorIds
        Set<String> authorIds = ExtractorUtils.extractToSet(comments, CommentEntity::getAuthorId);
        LoggerUtility.d(clazz, String.format("authorIds size: [%s]", authorIds.size()));

        // Get authors
        List<UserEntity> authors = userService.findByIdIn(authorIds.stream().toList());
        LoggerUtility.d(clazz, String.format("authors size: [%s]", authors.size()));

        // Get users tied to authorIds
        Map<String, UserEntity> usersById = ExtractorUtils.extractToMap(authors,
                                                                        UserEntity::getId,
                                                                        Function.identity());
        LoggerUtility.d(clazz, String.format("usersById size: [%s]", usersById.size()));

        // Extract all comments's id
        List<String> commentIds = ExtractorUtils.extractToList(comments, CommentEntity::getId);
        LoggerUtility.d(clazz, String.format("commentIds size: [%s]", commentIds.size()));

        // Get likedCommentIds
        Set<String> likedCommentIds = commentLikeService.getLikedCommentIds(commentIds, socialUser.getId());
        LoggerUtility.d(clazz, String.format("likedCommentIds size: [%s]", likedCommentIds.size()));
        return postProcessGetLatestCommentsByPostIds(comments, usersById, likedCommentIds);
    }

    private Map<String, List<CommentResponse>> postProcessGetLatestCommentsByPostIds(List<CommentEntity> comments,
                                                                                     Map<String, UserEntity> usersById,
                                                                                     Set<String> likedCommentIds) {
        LoggerUtility.d(clazz, "Execute method: [postProcessGetLatestCommentsByPostIds]");

        return comments.stream().map(comment -> {
            UserEntity author = usersById.get(comment.getAuthorId());
            boolean isLikedByCurrentUser = likedCommentIds.contains(comment.getId());
            return CommentMapper.toResponse(comment, author, isLikedByCurrentUser);
        })
                       .collect(Collectors.groupingBy(CommentResponse::postId,
                                                      Collectors.collectingAndThen(Collectors.toList(),
                                                                                   list -> list.stream()
                                                                                               .limit(UIConstants.MINIMUM_COMMENTS_PER_POST)
                                                                                               .toList())));
    }

    /**
     * Get Top-level comments in a post
     *
     * @param postId
     *            - Post ID
     * @param page
     *            - page
     * @return PagedResponse<CommentResponse>
     */
    public PagedResponse<CommentResponse> getTopLevelComments(String postId, int page) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [getTopLevelComments] postId: [%s] page: [%s]", postId, page));

        // Get auth user
        AuthUser authUser = authService.getAuthUser();

        // Get post
        PostEntity post = postService.getPostById(postId);

        // Get comments per page
        PageRequest pageRequest = PageRequest.of(page, UIConstants.MINIMUM_COMMENTS_PER_POST);
        Page<CommentEntity> toplevelCommentsPage = commentRepository.findByPostIdAndParentCommentIdIsNullOrderByCreatedAtAsc(post.getId(),
                                                                                                                             pageRequest);
        List<CommentEntity> topLevelComments = toplevelCommentsPage.getContent();
        LoggerUtility.d(clazz, String.format("topLevelComments size: [%s]", topLevelComments.size()));

        if (CollectionUtils.isEmpty(topLevelComments)) {
            LoggerUtility.d(clazz, "topLevelComments are empty");
            return new PagedResponse<>(Collections.emptyList(),
                                       page,
                                       UIConstants.MINIMUM_COMMENTS_PER_POST,
                                       0,
                                       0,
                                       false);
        }

        // Get social user
        UserEntity socialUser = userService.findById(authUser.id());
        return processCommentsToPagedResponse(socialUser, topLevelComments, toplevelCommentsPage);
    }

    /**
     * Get replies in a comment
     *
     * @param postId
     *            - Post ID
     * @param commentId
     *            - Comment ID
     * @param page
     *            - page
     * @return PagedResponse<CommentResponse>
     */
    public PagedResponse<CommentResponse> getReplies(String postId, String commentId, int page) {
        LoggerUtility.d(clazz,
                        String.format("Execute method: [getReplies] postId: [%s] commentId: [%s] page: [%s]",
                                      postId,
                                      commentId,
                                      page));

        // Get auth user
        AuthUser authUser = authService.getAuthUser();

        // Get post
        PostEntity post = postService.getPostById(postId);

        // Get comment
        CommentEntity parentComment = getCommentById(commentId);

        // Validate ownership
        if (!parentComment.getPostId().equals(post.getId())) {
            throw new BadRequestException(CommentErrorConstants.THE_COMMENT_DOES_NOT_BELONG_TO_THE_SPECIFIED_POST);
        }

        PageRequest pageRequest = PageRequest.of(page, UIConstants.MINIMUM_REPLIES_PER_COMMENT);
        Page<CommentEntity> repliesPage = commentRepository.findByParentCommentIdOrderByCreatedAtAsc(commentId,
                                                                                                     pageRequest);
        List<CommentEntity> replies = repliesPage.getContent();
        LoggerUtility.d(clazz, String.format("replies size: [%s]", replies.size()));

        if (CollectionUtils.isEmpty(replies)) {
            LoggerUtility.d(clazz, "replies are empty");
            return new PagedResponse<>(Collections.emptyList(),
                                       page,
                                       UIConstants.MINIMUM_REPLIES_PER_COMMENT,
                                       0,
                                       0,
                                       false);
        }

        // Get social user
        UserEntity socialUser = userService.findById(authUser.id());
        return processCommentsToPagedResponse(socialUser, replies, repliesPage);
    }

    private PagedResponse<CommentResponse> processCommentsToPagedResponse(UserEntity socialUser,
                                                                          List<CommentEntity> comments,
                                                                          Page<CommentEntity> commentsPage) {
        LoggerUtility.d(clazz, "processCommentsToPagedResponse");

        // Get authorIds
        Set<String> authorIds = ExtractorUtils.extractToSet(comments, CommentEntity::getAuthorId);
        LoggerUtility.d(clazz, String.format("authorIds size: [%s]", authorIds.size()));

        // Get authors
        List<UserEntity> authors = userService.findByIdIn(authorIds.stream().toList());
        LoggerUtility.d(clazz, String.format("authors size: [%s]", authors.size()));

        // Get users tied to authorIds
        Map<String, UserEntity> usersById = ExtractorUtils.extractToMap(authors,
                                                                        UserEntity::getId,
                                                                        Function.identity());
        LoggerUtility.d(clazz, String.format("usersById size: [%s]", usersById.size()));

        // Extract all comments's id
        List<String> commentIds = ExtractorUtils.extractToList(comments, CommentEntity::getId);
        LoggerUtility.d(clazz, String.format("commentIds size: [%s]", commentIds.size()));

        // Get likedCommentIds
        Set<String> likedCommentIds = commentLikeService.getLikedCommentIds(commentIds, socialUser.getId());
        LoggerUtility.d(clazz, String.format("likedCommentIds size: [%s]", likedCommentIds.size()));

        List<CommentResponse> response = comments.stream().map(comment -> {
            UserEntity author = usersById.get(comment.getAuthorId());
            boolean isLikedByCurrentUser = likedCommentIds.contains(comment.getId());
            return CommentMapper.toResponse(comment, author, isLikedByCurrentUser);
        }).toList();

        return new PagedResponse<>(response,
                                   commentsPage.getNumber(),
                                   commentsPage.getSize(),
                                   commentsPage.getTotalElements(),
                                   commentsPage.getTotalPages(),
                                   commentsPage.hasNext());
    }

    /**
     * Get comment by comment ID
     *
     * @param commentId
     *            - Comment ID
     * @return CommentEntity or null
     */
    public CommentEntity getCommentById(String commentId) {
        return commentRepository.findById(commentId)
                                .orElseThrow(() -> new NotFoundException(CommentErrorConstants.COMMENT_NOT_FOUND));
    }
}
