package com.johnmartin.social.service;

import java.util.ArrayList;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

import com.johnmartin.social.constants.api.ApiErrorMessages;
import com.johnmartin.social.dto.AuthUser;
import com.johnmartin.social.dto.request.CreatePostRequest;
import com.johnmartin.social.dto.response.PostResponse;
import com.johnmartin.social.entities.PostEntity;
import com.johnmartin.social.exception.BadRequestException;
import com.johnmartin.social.exception.ResourceNotFoundException;
import com.johnmartin.social.mapper.PostMapper;
import com.johnmartin.social.repository.PostRepository;
import com.johnmartin.social.security.AuthContext;
import com.johnmartin.social.utilities.LoggerUtility;

@Service
public class PostService {

    private static final Class<PostService> clazz = PostService.class;

    @Autowired
    private PostRepository postRepository;

    /**
     * Create a post
     *
     * @param request
     *            - CreatePostRequest
     * @return PostResponse
     */
    public PostResponse createPost(CreatePostRequest request) {
        LoggerUtility.d(clazz, String.format("Execute method: [createPost] request: [%s]", request));

        AuthUser authUser = AuthContext.get();

        if (request == null) {
            throw new BadRequestException(ApiErrorMessages.INVALID_REQUEST);
        }

        if (StringUtils.isBlank(request.getDescription())) {
            throw new BadRequestException(ApiErrorMessages.Post.POST_DESCRIPTION_IS_REQUIRED);
        }

        PostEntity createdPost = new PostEntity();
        createdPost.setTitle(request.getTitle());
        createdPost.setDescription(request.getDescription());
        createdPost.setAuthorId(authUser.getId());
        createdPost.setAuthor(authUser.getFirstName() + " " + authUser.getLastName());
        createdPost.setAuthorProfileImageUrl(authUser.getProfileImageUrl());
        createdPost.setLikesCount(0);
        createdPost.setCommentsCount(0);
        createdPost.setSharesCount(0);

        LoggerUtility.t(clazz, String.format("createdPost: [%s]", createdPost));

        // ID and Dates are generated by MongoDB after insertion
        PostEntity postToBeReturned = postRepository.save(createdPost);
        LoggerUtility.t(clazz, String.format("postToBeReturned: [%s]", postToBeReturned));
        return PostMapper.toResponse(postToBeReturned, new ArrayList<>(), authUser.getId());
    }

    /**
     * Increment comments count
     * 
     * @param postId
     *            - Post ID
     */
    public void incrementCommentsCount(String postId) {
        PostEntity post = getPostById(postId);
        postRepository.incrementCommentsCount(post.getId());
    }

    /**
     * Decrement comments count
     *
     * @param postId
     *            - Post ID
     */
    public void decrementCommentsCount(String postId) {
        PostEntity post = getPostById(postId);
        postRepository.decrementCommentsCount(post.getId());
    }

    /**
     * Get post by post ID
     *
     * @param postId
     *            - Post ID
     * @return PostEntity or null
     */
    public PostEntity getPostById(String postId) {
        return postRepository.findById(postId)
                             .orElseThrow(() -> new ResourceNotFoundException(ApiErrorMessages.Post.POST_NOT_FOUND));
    }

    /**
     * Get posts with 10 latest comments
     *
     * @param pageRequest
     *            - Page Request
     * @return Page of Entity
     */
    public Page<PostEntity> getPostsWithLatestComments(PageRequest pageRequest) {
        return postRepository.findAllByOrderByCreatedAtDesc(pageRequest);
    }

    /**
     * Like a post
     *
     * @param userId
     *            - User ID
     * @param postId
     *            - Post ID
     */
    public void likePost(String userId, String postId) {
        postRepository.likePost(userId, postId);
    }

    /**
     * Unlike a post
     * 
     * @param userId
     *            - User ID
     * @param postId
     *            - Post ID
     */
    public void unlikePost(String userId, String postId) {
        postRepository.unlikePost(userId, postId);
    }

    /**
     * Delete a post
     * 
     * @param postId
     *            - Post ID
     */
    public void deletePost(String postId) {
        postRepository.deleteById(postId);
    }

    /**
     * Save a post
     * 
     * @param post
     *            - Post
     * @return PostEntity
     */
    public PostEntity savePost(PostEntity post) {
        return postRepository.save(post);
    }
}
