package com.johnmartin.social.service;

import java.util.ArrayList;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

import com.johnmartin.social.constants.api.ApiErrorMessages;
import com.johnmartin.social.dto.AuthUser;
import com.johnmartin.social.dto.request.CreatePostRequest;
import com.johnmartin.social.dto.response.PostResponse;
import com.johnmartin.social.entities.PostEntity;
import com.johnmartin.social.entities.UserEntity;
import com.johnmartin.social.exception.BadRequestException;
import com.johnmartin.social.exception.NotFoundException;
import com.johnmartin.social.exception.UnauthorizedException;
import com.johnmartin.social.mapper.PostMapper;
import com.johnmartin.social.repository.PostRepository;
import com.johnmartin.social.security.AuthContext;
import com.johnmartin.social.utilities.LoggerUtility;

@Service
public class PostService {

    private static final Class<PostService> clazz = PostService.class;

    private final PostRepository postRepository;
    private final UserService userService;

    public PostService(PostRepository postRepository, UserService userService) {
        this.postRepository = postRepository;
        this.userService = userService;
    }

    /**
     * Create a post
     *
     * @param request
     *            - CreatePostRequest
     * @return PostResponse
     */
    public PostResponse createPost(CreatePostRequest request) {
        LoggerUtility.d(clazz, String.format("Execute method: [createPost] request: [%s]", request));

        if (request == null) {
            LoggerUtility.d(clazz, "Request is null, will not proceed method call");
            throw new BadRequestException(ApiErrorMessages.INVALID_REQUEST);
        }

        AuthUser authUser = AuthContext.get();
        if (authUser == null) {
            LoggerUtility.d(clazz, "Auth user is null, will throw unauthorized exception");
            throw new UnauthorizedException(ApiErrorMessages.User.USER_IS_NOT_AUTHENTICATED);
        }

        // Get social user
        UserEntity user = userService.findByEmail(authUser.email());

        LoggerUtility.d(clazz, "Creating a post");
        PostEntity createdPost = new PostEntity();
        createdPost.setTitle(request.title());
        createdPost.setDescription(request.description());
        createdPost.setAuthorId(user.getId());
        createdPost.setLikesCount(0);
        createdPost.setCommentsCount(0);
        createdPost.setSharesCount(0);

        LoggerUtility.t(clazz, String.format("createdPost: [%s]", createdPost));

        // ID and Dates are generated by MongoDB after insertion
        PostEntity postToBeReturned = postRepository.save(createdPost);
        LoggerUtility.t(clazz, String.format("postToBeReturned: [%s]", postToBeReturned));
        return PostMapper.toResponse(postToBeReturned, new ArrayList<>(), user);
    }

    /**
     * Increment comments count
     * 
     * @param postId
     *            - Post ID
     */
    public void incrementCommentsCount(String postId) {
        LoggerUtility.d(clazz, String.format("Execute method: [incrementCommentsCount] postId: [%s]", postId));
        PostEntity post = getPostById(postId);
        postRepository.incrementCommentsCount(post.getId());
    }

    /**
     * Decrement comments count
     *
     * @param postId
     *            - Post ID
     */
    public void decrementCommentsCount(String postId) {
        LoggerUtility.d(clazz, String.format("Execute method: [decrementCommentsCount] postId: [%s]", postId));
        PostEntity post = getPostById(postId);
        postRepository.decrementCommentsCount(post.getId());
    }

    /**
     * Get post by post ID
     *
     * @param postId
     *            - Post ID
     * @return PostEntity or null
     */
    public PostEntity getPostById(String postId) {
        return postRepository.findById(postId)
                             .orElseThrow(() -> new NotFoundException(ApiErrorMessages.Post.POST_NOT_FOUND));
    }

    /**
     * Get posts with 10 latest comments
     *
     * @param pageRequest
     *            - Page Request
     * @return Page of Entity
     */
    public Page<PostEntity> getPostsWithLatestComments(PageRequest pageRequest) {
        LoggerUtility.d(clazz, "Execute method: [getPostsWithLatestComments]");
        return postRepository.findAllByOrderByCreatedAtDesc(pageRequest);
    }

    /**
     * Like a post
     *
     * @param userId
     *            - User ID
     * @param postId
     *            - Post ID
     */
    public void likePost(String userId, String postId) {
        LoggerUtility.d(clazz, String.format("Execute method: [likePost] userId: [%s] postId: [%s]", userId, postId));
        postRepository.likePost(userId, postId);
    }

    /**
     * Unlike a post
     * 
     * @param userId
     *            - User ID
     * @param postId
     *            - Post ID
     */
    public void unlikePost(String userId, String postId) {
        LoggerUtility.d(clazz, String.format("Execute method: [unlikePost] userId: [%s] postId: [%s]", userId, postId));
        postRepository.unlikePost(userId, postId);
    }

    /**
     * Delete a post
     * 
     * @param postId
     *            - Post ID
     */
    public void deletePost(String postId) {
        LoggerUtility.d(clazz, String.format("Execute method: [deletePost] postId: [%s]", postId));
        postRepository.deleteById(postId);
    }

    /**
     * Save a post
     * 
     * @param post
     *            - Post
     * @return PostEntity
     */
    public PostEntity savePost(PostEntity post) {
        LoggerUtility.d(clazz, String.format("Execute method: [savePost] post: [%s]", post));
        return postRepository.save(post);
    }
}
